// CommandsModal — Browse, view, edit, add, delete command .md files
// Sidebar list grouped by folder (collapsible) + content viewer layout.
// New commands are generated by Claude CLI from a description.

import React, { useState, useEffect, useCallback } from 'react';
import Modal from './Modal.jsx';

const COMMAND_TEMPLATE = '# `!command_name`\n\n**Purpose:** Describe what this command does.\n\n**Syntax:** `!command_name [options] {prompt}`\n\n---\n\n## Details\n\nAdd detailed instructions here.\n';

function CommandFolder({ folder, commands, activeCommand, onSelect, onNewCommand, defaultOpen }) {
  const [open, setOpen] = useState(defaultOpen || false);
  return (
    <div className="commands-folder">
      <button
        className={'commands-folder-header' + (open ? ' open' : '')}
        onClick={() => setOpen(o => !o)}
      >
        <svg className="commands-folder-chevron" width="10" height="10" viewBox="0 0 10 10" fill="none">
          <path d="M3 2l4 3-4 3" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
        <span className="commands-folder-name">{folder}</span>
        <span className="commands-folder-count">{commands.length}</span>
        <button
          className="commands-folder-add-btn"
          title={'New command in ' + folder}
          onClick={(e) => { e.stopPropagation(); onNewCommand(folder); }}
        >+</button>
      </button>
      {open && (
        <div className="commands-folder-items">
          {commands.map(cmd => (
            <div
              key={cmd.name + (cmd.subfolder || '')}
              className={'commands-list-item' + (activeCommand && activeCommand.name === cmd.name ? ' active' : '')}
              onClick={() => onSelect(cmd)}
            >
              <span className="commands-item-name">
                {cmd.subfolder ? <span className="commands-item-subfolder">{cmd.subfolder}/</span> : null}
                !{cmd.name}
              </span>
              <div className="commands-item-purpose">{cmd.purpose || ''}</div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function CommandViewer({ cmd, onEdit, onDelete }) {
  return (
    <>
      <div className="commands-viewer-header">
        <h2 className="commands-viewer-title">{cmd.title || cmd.name}</h2>
        <div className="commands-viewer-actions">
          <button className="commands-action-btn" onClick={onEdit}>Edit</button>
          <button className="commands-action-btn commands-delete-btn" onClick={onDelete}>Delete</button>
        </div>
      </div>
      {cmd.purpose && (
        <div className="commands-viewer-purpose">
          <span className="commands-meta-label">Purpose: </span>
          <span>{cmd.purpose}</span>
        </div>
      )}
      {cmd.syntax && (
        <div className="commands-viewer-syntax">
          <span className="commands-meta-label">Syntax: </span>
          <code>{cmd.syntax}</code>
        </div>
      )}
      <pre className="commands-viewer-content">{cmd.content || ''}</pre>
    </>
  );
}

function CommandEditor({ cmd, onSave, onCancel }) {
  const [name, setName] = useState(cmd ? cmd.name : '');
  const [content, setContent] = useState(cmd ? (cmd.content || '') : COMMAND_TEMPLATE);

  function handleSave() {
    const finalName = cmd ? cmd.name : name.trim();
    if (!finalName) { alert('Command name is required'); return; }
    onSave(finalName, content);
  }

  return (
    <>
      <div className="commands-viewer-header">
        <h2 className="commands-viewer-title">
          {cmd ? 'Editing: ' + cmd.name : 'New Command'}
        </h2>
      </div>
      {!cmd && (
        <div className="commands-editor-field">
          <label>Command Name:</label>
          <input
            className="commands-editor-input"
            type="text"
            placeholder="my_command"
            value={name}
            onChange={e => setName(e.target.value)}
          />
        </div>
      )}
      <div className="commands-editor-field">
        <label>Markdown Content:</label>
        <textarea
          className="commands-editor-textarea"
          value={content}
          onChange={e => setContent(e.target.value)}
        />
      </div>
      <div className="commands-editor-buttons">
        <button className="commands-save-btn" onClick={handleSave}>Save</button>
        <button className="commands-action-btn" onClick={onCancel}>Cancel</button>
      </div>
    </>
  );
}

function CommandGenerator({ folder, onGenerated, onCancel }) {
  const api = window.electronAPI || null;
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState(null);

  function handleGenerate() {
    const trimmedName = name.trim();
    const trimmedDesc = description.trim();
    if (!trimmedName) { alert('Command name is required'); return; }
    if (!trimmedDesc) { alert('Description is required'); return; }
    if (!api) return;

    setGenerating(true);
    setError(null);

    api.generateCommand(trimmedDesc, folder.folder, trimmedName).then(result => {
      setGenerating(false);
      if (result && result.success) {
        onGenerated(result.name);
      } else {
        setError((result && result.error) || 'Generation failed');
      }
    }).catch(err => {
      setGenerating(false);
      setError(err.message || 'Generation failed');
    });
  }

  return (
    <>
      <div className="commands-viewer-header">
        <h2 className="commands-viewer-title">
          New Command in {folder.folder}
        </h2>
      </div>
      <div className="commands-editor-field">
        <label>Command Name:</label>
        <input
          className="commands-editor-input"
          type="text"
          placeholder="my_command"
          value={name}
          onChange={e => setName(e.target.value)}
          disabled={generating}
        />
      </div>
      <div className="commands-editor-field">
        <label>Describe what this command should do:</label>
        <textarea
          className="commands-editor-textarea commands-generator-textarea"
          placeholder="Describe the command's purpose, when it should be used, what steps it should follow, and what output it should produce..."
          value={description}
          onChange={e => setDescription(e.target.value)}
          disabled={generating}
        />
      </div>
      {error && (
        <div className="commands-generator-error">{error}</div>
      )}
      <div className="commands-editor-buttons">
        <button
          className="commands-save-btn"
          onClick={handleGenerate}
          disabled={generating || !name.trim() || !description.trim()}
        >
          {generating ? 'Generating...' : 'Generate Command'}
        </button>
        <button className="commands-action-btn" onClick={onCancel} disabled={generating}>Cancel</button>
      </div>
      {generating && (
        <div className="commands-generator-status">
          Claude is reading CLAUDE.md and existing commands to generate a comprehensive command file...
        </div>
      )}
    </>
  );
}

export default function CommandsModal({ onClose, projectDir }) {
  const api = window.electronAPI || null;

  const [synapseGroups, setSynapseGroups] = useState([]);
  const [projectGroups, setProjectGroups] = useState([]);
  const [activeCommand, setActiveCommand] = useState(null);
  const [activeCommandsDir, setActiveCommandsDir] = useState(null);
  const [viewerState, setViewerState] = useState('placeholder');
  const [newCommandFolder, setNewCommandFolder] = useState(null);
  const [showNewFolderInput, setShowNewFolderInput] = useState(false);
  const [newFolderName, setNewFolderName] = useState('');

  const loadCommands = useCallback(() => {
    if (!api) return;
    api.listCommands().then(groups => setSynapseGroups(groups || []));
    if (projectDir) {
      api.listProjectCommands(projectDir).then(groups => setProjectGroups(groups || []));
    }
  }, [api, projectDir]);

  useEffect(() => { loadCommands(); }, [loadCommands]);

  function selectCommand(cmd, commandsDir) {
    if (!api) return;
    const getter = commandsDir ? api.getCommand(cmd.name, commandsDir) : api.getCommand(cmd.name);
    getter.then(full => {
      if (!full) { setViewerState('placeholder'); setActiveCommand(null); return; }
      setActiveCommand(full);
      setActiveCommandsDir(commandsDir);
      setViewerState('view');
    });
  }

  function handleDelete() {
    if (!activeCommand || !api) return;
    if (!confirm('Delete command "!' + activeCommand.name + '"?')) return;
    const deleter = activeCommandsDir
      ? api.deleteCommand(activeCommand.name, activeCommandsDir)
      : api.deleteCommand(activeCommand.name);
    deleter.then(() => {
      loadCommands();
      setActiveCommand(null);
      setViewerState('placeholder');
    });
  }

  function handleSave(name, content) {
    if (!api) return;
    const saver = activeCommandsDir
      ? api.saveCommand(name, content, activeCommandsDir)
      : api.saveCommand(name, content);
    saver.then(() => {
      loadCommands();
      selectCommand({ name }, activeCommandsDir);
    });
  }

  function handleNewFolder() {
    setShowNewFolderInput(true);
    setNewFolderName('');
  }

  function submitNewFolder() {
    if (!newFolderName.trim() || !api) return;
    api.createCommandFolder(newFolderName.trim()).then(result => {
      if (result && result.success) {
        loadCommands();
        setShowNewFolderInput(false);
        setNewFolderName('');
      } else if (result && result.error) {
        // Show inline — alert may also be blocked
        setNewFolderName('');
      }
    });
  }

  function handleNewCommandInFolder(folder, commandsDir) {
    setActiveCommand(null);
    setActiveCommandsDir(commandsDir);
    setNewCommandFolder({
      folder,
      dir: commandsDir,
      isProjectFolder: !!commandsDir,
    });
    setViewerState('generate');
  }

  function handleGenerated(commandName) {
    loadCommands();
    // Open the generated command
    selectCommand({ name: commandName }, newCommandFolder?.isProjectFolder ? newCommandFolder.dir : null);
    setNewCommandFolder(null);
  }

  return (
    <Modal title="Commands" onClose={onClose} className="commands-modal">
      <div className="commands-layout">
        <div className="commands-sidebar">
          <div className="commands-sidebar-header">
            <span className="commands-section-title">Commands</span>
            <button className="commands-add-btn" onClick={handleNewFolder}>+ Folder</button>
          </div>
          <div className="commands-list">
            {showNewFolderInput && (
              <div className="commands-new-folder-input">
                <input
                  autoFocus
                  className="commands-editor-input"
                  type="text"
                  placeholder="Folder name"
                  value={newFolderName}
                  onChange={e => setNewFolderName(e.target.value)}
                  onKeyDown={e => {
                    if (e.key === 'Enter') submitNewFolder();
                    if (e.key === 'Escape') setShowNewFolderInput(false);
                  }}
                />
                <button className="commands-folder-add-btn" style={{ opacity: 1 }} onClick={submitNewFolder}>✓</button>
                <button className="commands-folder-add-btn" style={{ opacity: 1 }} onClick={() => setShowNewFolderInput(false)}>✕</button>
              </div>
            )}
            {synapseGroups.map(group => (
              <CommandFolder
                key={group.folder}
                folder={group.folder}
                commands={group.commands}
                activeCommand={activeCommand}
                onSelect={cmd => selectCommand(cmd, null)}
                onNewCommand={(folder) => handleNewCommandInFolder(folder, null)}
              />
            ))}
            {projectGroups.map(group => (
              <CommandFolder
                key={'project-' + group.folder}
                folder={group.folder}
                commands={group.commands}
                activeCommand={activeCommand}
                onSelect={cmd => selectCommand(cmd, projectDir + '/_commands')}
                onNewCommand={(folder) => handleNewCommandInFolder(folder, projectDir + '/_commands')}
              />
            ))}
            {synapseGroups.length === 0 && projectGroups.length === 0 && (
              <div className="commands-empty">No commands found</div>
            )}
          </div>
        </div>

        <div className="commands-viewer">
          {viewerState === 'placeholder' && (
            <div className="commands-viewer-placeholder">
              Select a command to view documentation
            </div>
          )}
          {viewerState === 'view' && activeCommand && (
            <CommandViewer
              cmd={activeCommand}
              onEdit={() => setViewerState('edit')}
              onDelete={handleDelete}
            />
          )}
          {viewerState === 'edit' && activeCommand && (
            <CommandEditor
              cmd={activeCommand}
              onSave={handleSave}
              onCancel={() => setViewerState('view')}
            />
          )}
          {viewerState === 'generate' && newCommandFolder && (
            <CommandGenerator
              folder={newCommandFolder}
              onGenerated={handleGenerated}
              onCancel={() => { setViewerState('placeholder'); setNewCommandFolder(null); }}
            />
          )}
        </div>
      </div>
    </Modal>
  );
}
